{% set name = "optking" %}
{% set version = "0.4.2" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/psi-rking/optking/archive/{{ version }}.tar.gz
  sha256: 1911aeb8f2459cf8caa39d604158bc04fbf1327e3454bb78d43440c08f5f5a90

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - numpy >=1.21
    - qcelemental >=0.21.0
    - qcengine >=0.21.0
    - msgpack-python >=1.0
    - pydantic >=1.10.17

test:
  imports:
    - optking
  commands:
    # - pip check
    - pytest -k test_lj_external_gradient
  source_files:
    - optking/tests/test_opthelper.py
  requires:
    - python {{ python_min }}
    - pip
    - pytest >=4.0.0


about:
  home: https://github.com/psi-rking/optking
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A molecular optimizer for Quantum Chemistry calculations.
  dev_url: https://github.com/psi-rking/optking.git
  doc_url: https://optking.readthedocs.io/en/latest/
  doc_source_url: https://github.com/psi-rking/optking/blob/master/docs/source/index.rst

extra:
  recipe-maintainers:
    - AlexHeide
