{% set name = "optking" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/psi-rking/optking/archive/{{ version }}.tar.gz
  sha256: 573ba580ff34282f199335717c73e700ff678ff7032c84a932732181145e236b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.21
    - qcelemental >=0.21.0
    - qcengine >=0.21.0
    - msgpack-python >=1.0

test:
  imports:
    - optking
  commands:
    - pip check
    - pytest -k test_lj_external_gradient
  source_files:
    - optking/tests/test_opthelper.py
  requires:
    - pip
    - pytest >=4.0.0


about:
  home: https://github.com/psi-rking/optking
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A molecular optimizer for Quantum Chemistry calculations.
  dev_url: https://github.com/psi-rking/optking.git
  doc_url: https://optking.readthedocs.io/en/latest/
  doc_source_url: https://github.com/psi-rking/optking/blob/master/docs/source/index.rst

extra:
  recipe-maintainers:
    - AlexHeide
